[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sigils"
version = "0.1.4"
authors = [
    {name = "Rafael Jesús Guillén Osorio", email = "arthexis@gmail.com"},
]
description = "Extract, resolve, replace and define [SIGILS] in any text."
readme = "README.rst"
requires-python = ">=3.9"
keywords = ["utils", "sigils", "string", "text", "magic", "context"]
license = {file = "LICENSE"}
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Libraries',
    'Topic :: Text Processing',
    'Topic :: Utilities',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
dependencies = [
    'lark',
    'lark-parser',
    'lru-dict'
]

[urls]
Source = "https://github.com/arthexis/sigils"

[project.optional-dependencies]
django = ["Django>=3.2"]
dev = [
    "pytest", 
    "pytest-cov", 
    "python-dotenv"
]

[project.scripts]
sigils = "sigils.cli:main"

